export const items = [
  {
    id: 1,
    imges: "/public/data/01.png",
    price: "$2.15",
    titles: "Muesli Fitness Energy, gluten free",
    KG: "500g",
  },
  {
    id: 2,
    imges: "/public/data/02 (1).png",
    price: "$1.15",
    titles: "Muesli Fitness Energy",
    KG: "200g",
  },
  {
    id: 3,
    imges: "/public/data/02.png",
    price: "$3.12 ",
    titles: "Fresh orange Klementina, Spain",
    KG: "1KG",
  },
  {
    id: 4,
    imges: "/public/data/03.png",
    price: "$0.80",
    titles: "Pepsi soda classic, can",
    KG: "330ml",
  },
  {
    id: 5,
    imges: "/public/data/04.png",
    price: "$2.99",
    titles: "Mozzarella mini cheese Granaloro",
    KG: "250g",
  },
  {
    id: 6,
    imges: "/public/data/07 (1).png",
    price: "$1.99",
    titles: "Fresh mango, Spain",
    KG: "1 mango",
  },
  {
    id: 7,
    imges: "/public/data/11.png",
    price: "$3.40",
    titles: "Fresh red grapefruit",
    KG: "1kg",
  },
  {
    id: 8,
    imges: "/public/data/12.png",
    price: "$2.59",
    titles: "Soft creme cheese with greens Exquisa",
    KG: "150g",
  },
];
